In [1]:
import os
import pandas as pd
import requests

In [2]:
data_dir = '../data/'
# These will be downloaded

# https://population.un.org/wpp/Download/Files/2_Indicators%20(Probabilistic%20Projections)/UN_PPP2019_Output_PopTot.xls
chinese_total_pop = 'UN_PPP2019_Output_PopTot.xls'

# https://population.un.org/wpp/Download/Files/2_Indicators%20(Probabilistic%20Projections)/UN_PPP2019_Output_Pop15-64.xls
chinese_working_pop = 'UN_PPP2019_Output_Pop15-64.xls'

In [3]:
total_pop_url = 'https://population.un.org/wpp/Download/Files/2_Indicators%20(Probabilistic%20Projections)/UN_PPP2019_Output_PopTot.xlsx'

#total_pop_url = 'https://population.un.org/wpp/Download/Files/2_Indicators%20(Probabilistic%20Projections)/UN_PPP2019_Output_PopTot.xls'


#working_pop_url = 'https://population.un.org/wpp/Download/Files/2_Indicators%20(Probabilistic%20Projections)/UN_PPP2019_Output_Pop15-64.xls'

working_pop_url = 'https://population.un.org/wpp/Download/Files/2_Indicators%20(Probabilistic%20Projections)/UN_PPP2019_Output_Pop15-64.xlsx'
total_pop_file_name = 'UN_PPP2019_Output_PopTot.xls'
working_pop_file_name = 'UN_PPP2019_Output_Pop15-64.xls'

In [4]:
my_req = requests.get(total_pop_url)

with open(os.path.join(data_dir, total_pop_file_name), 'wb') as f:
    f.write(my_req.content)

In [5]:
my_req = requests.get(working_pop_url)

with open(os.path.join(data_dir, working_pop_file_name), 'wb') as f:
    f.write(my_req.content)

In [6]:
fp_chinese_total = os.path.join(data_dir, total_pop_file_name) 
fp_chinese_working = os.path.join(data_dir, working_pop_file_name)

In [7]:
df_total = pd.read_excel(fp_chinese_total,  sheet_name='Median', skiprows=16)
df_working = pd.read_excel(fp_chinese_working, sheet_name='Median', skiprows=16)

In [8]:
df_working.head(30)

,Index,Variant,"Region, subregion, country or area *",Notes,Unnamed: 4,Type,Unnamed: 6,2020,2025,2030,...,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
0,1,Median PI,WORLD,NaN,900,World,0,5.08354e+06,5.32053e+06,5.53154e+06,...,6.20016e+06,6.28757e+06,6.37572e+06,6.45125e+06,6.49811e+06,6.52122e+06,6.53102e+06,6.53631e+06,6.53467e+06,6.52103e+06
1,2,Median PI,UN development groups,a,1803,Label/Separator,900,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,3,Median PI,More developed regions,b,901,Development Group,1803,819200,807347,794211,...,728927,720338,717434,714673,707983,701011,695990,693045,691655,690754
3,4,Median PI,Less developed regions,c,902,Development Group,1803,4.26434e+06,4.51318e+06,4.73733e+06,...,5.47124e+06,5.56723e+06,5.65829e+06,5.73658e+06,5.79013e+06,5.82021e+06,5.83503e+06,5.84326e+06,5.84301e+06,5.83027e+06
4,5,Median PI,Least developed countries,d,941,Development Group,902,609016,696034,787423,...,1.28658e+06,1.38312e+06,1.47474e+06,1.56075e+06,1.64093e+06,1.71505e+06,1.7822e+06,1.84163e+06,1.89306e+06,1.93644e+06
5,6,Median PI,"Less developed regions, excluding least develo...",e,934,Development Group,902,3.65533e+06,3.81715e+06,3.9499e+06,...,4.18465e+06,4.18411e+06,4.18354e+06,4.17583e+06,4.1492e+06,4.10517e+06,4.05283e+06,4.00163e+06,3.94995e+06,3.89384e+06
6,7,Median PI,"Less developed regions, excluding China",NaN,948,Development Group,1803,3.22954e+06,3.48488e+06,3.73021e+06,...,4.67597e+06,4.80335e+06,4.91685e+06,5.01463e+06,5.09139e+06,5.14894e+06,5.18993e+06,5.21854e+06,5.23502e+06,5.23827e+06
7,8,Median PI,Land-locked Developing Countries (LLDC),f,1636,Special other,1803,305405,348501,395411,...,639408,683580,724903,762820,795532,822932,846182,865671,881198,892364
8,9,Median PI,Small Island Developing States (SIDS),g,1637,Special other,1803,47207,49243.9,50782.4,...,55784.4,56008.2,56008.9,55909.1,55640.1,55190.8,54627.5,53970.3,53235.3,52404.9
9,10,Median PI,World Bank income groups,NaN,1802,Label/Separator,900,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,11,Median PI,High-income countries,h,1503,Income Group,1802,821117,818020,810613,...,762414,753222,747758,743931,737676,731755,727631,724557,722242,720408
11,12,Median PI,Middle-income countries,h,1517,Income Group,1802,3.831e+06,3.99925e+06,4.14017e+06,...,4.41961e+06,4.42876e+06,4.43864e+06,4.43908e+06,4.41967e+06,4.3831e+06,4.3387e+06,4.29603e+06,4.2531e+06,4.2054e+06
12,13,Median PI,Upper-middle-income countries,h,1502,Income Group,1517,1.82564e+06,1.8442e+06,1.84658e+06,...,1.64883e+06,1.60872e+06,1.58044e+06,1.5535e+06,1.51767e+06,1.47181e+06,1.42532e+06,1.38734e+06,1.35566e+06,1.32539e+06
13,14,Median PI,Lower-middle-income countries,h,1501,Income Group,1517,2.00536e+06,2.15505e+06,2.29359e+06,...,2.77078e+06,2.82003e+06,2.8582e+06,2.88558e+06,2.90201e+06,2.91128e+06,2.91338e+06,2.90868e+06,2.89744e+06,2.88001e+06
14,15,Median PI,Low-income countries,h,1500,Income Group,1802,429535,501272,578698,...,1.01569e+06,1.10306e+06,1.18675e+06,1.26565e+06,1.33815e+06,1.40373e+06,1.46204e+06,1.51306e+06,1.55667e+06,1.59256e+06
15,16,Median PI,No income group available,NaN,1518,Income Group,1802,1891.94,1984.83,2053.71,...,2455.63,2529.73,2568.92,2591.53,2612.31,2636.54,2652.9,2662.28,2660.07,2648.66
16,17,Median PI,Geographic regions,i,1840,Label/Separator,900,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,18,Median PI,Africa,j,903,Region,1840,752672,863297,988438,...,1.69745e+06,1.84749e+06,1.99476e+06,2.13533e+06,2.26511e+06,2.38266e+06,2.49131e+06,2.59057e+06,2.67845e+06,2.75308e+06
18,19,Median PI,Asia,k,935,Region,1840,3.13982e+06,3.25655e+06,3.33792e+06,...,3.33096e+06,3.28397e+06,3.23627e+06,3.18305e+06,3.11598e+06,3.0389e+06,2.95683e+06,2.87783e+06,2.80136e+06,2.72509e+06
19,20,Median PI,Europe,l,908,Region,1840,484660,472572,460234,...,392783,385242,382297,378975,372173,364123,357285,352751,349958,347563
20,21,Median PI,Latin America and the Caribbean,m,904,Region,1840,439059,457581,471821,...,481015,471403,460401,448970,437405,424728,411306,398027,385278,373093
21,22,Median PI,Northern America,n,905,Region,1840,240181,241967,243162,...,261362,261772,263093,264867,266465,269052,271879,274085,275942,277920
22,23,Median PI,Oceania,o,909,Region,1840,27152.3,28564.8,29965.9,...,36591.7,37699.1,38893.6,40060.5,40980,41759.5,42410,43049.5,43682,44271.8
23,24,Median PI,Sustainable Development Goal (SDG) regions,p,1828,Label/Separator,900,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,25,Median PI,SUB-SAHARAN AFRICA,NaN,947,SDG region,1828,601137,698307,806994,...,1.45121e+06,1.58967e+06,1.72501e+06,1.85446e+06,1.97565e+06,2.08853e+06,2.19342e+06,2.28857e+06,2.37245e+06,2.44428e+06
25,26,Median PI,Eastern Africa,NaN,910,Subregion,947,246156,287801,333432,...,590947,641884,689955,734744,775909,813622,847716,877409,902571,923474
26,27,Median PI,Burundi,NaN,108,Country/Area,910,6226.96,7353.82,8741.01,...,17212.1,19093.8,21097.3,23091.9,24967,26697,28347.9,29931.9,31422.6,32789.2
27,28,Median PI,Comoros,NaN,174,Country/Area,910,503.276,569.802,642.93,...,1011.34,1080.99,1147.96,1209.46,1263.8,1309.95,1351.12,1386.67,1415.57,1437.06
28,29,Median PI,Djibouti,NaN,262,Country/Area,910,655.848,707.224,759.957,...,880.212,882.484,882.699,880.777,877.383,862.986,845.912,829.679,815.991,803.936
29,30,Median PI,Eritrea,NaN,232,Country/Area,910,1928.14,2234.29,2546.03,...,4154.17,4462.04,4771.6,5010.57,5163.74,5328.1,5479.54,5614.06,5706.86,5747.76

In [9]:
df_total.head(30)

,Index,Variant,"Region, subregion, country or area",Notes,Unnamed: 4,Type,Unnamed: 6,2020,2025,2030,...,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
0,1,Median PI,WORLD,NaN,900,World,0,7.7948e+06,8.18444e+06,8.54849e+06,...,9.9581e+06,1.01515e+07,1.03179e+07,1.04592e+07,1.05773e+07,1.06739e+07,1.07507e+07,1.08099e+07,1.08519e+07,1.08754e+07
1,2,Median PI,UN development groups,a,1803,Label/Separator,900,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,3,Median PI,More developed regions,b,901,Development Group,1803,1.2733e+06,1.2815e+06,1.28601e+06,...,1.27397e+06,1.26717e+06,1.26031e+06,1.25423e+06,1.24936e+06,1.24598e+06,1.24402e+06,1.24334e+06,1.24359e+06,1.2443e+06
3,4,Median PI,Less developed regions,c,902,Development Group,1803,6.52149e+06,6.90293e+06,7.26248e+06,...,8.68412e+06,8.8843e+06,9.05757e+06,9.20501e+06,9.32792e+06,9.42792e+06,9.50664e+06,9.56655e+06,9.60827e+06,9.6311e+06
4,5,Median PI,Least developed countries,d,941,Development Group,902,1.05744e+06,1.18238e+06,1.31376e+06,...,2.01934e+06,2.15963e+06,2.29625e+06,2.42768e+06,2.55255e+06,2.66968e+06,2.77805e+06,2.87719e+06,2.96679e+06,3.04678e+06
5,6,Median PI,"Less developed regions, excluding least develo...",e,934,Development Group,902,5.46406e+06,5.72056e+06,5.94872e+06,...,6.66479e+06,6.72467e+06,6.76131e+06,6.77733e+06,6.77538e+06,6.75825e+06,6.72859e+06,6.68937e+06,6.64148e+06,6.58432e+06
6,7,Median PI,"Less developed regions, excluding China",NaN,948,Development Group,1803,5.05021e+06,5.41261e+06,5.76538e+06,...,7.284e+06,7.52151e+06,7.7333e+06,7.91875e+06,8.07894e+06,8.2154e+06,8.32887e+06,8.42061e+06,8.49102e+06,8.54119e+06
7,8,Median PI,Land-locked Developing Countries (LLDC),f,1636,Special other,1803,533143,595213,659183,...,991619,1.05443e+06,1.11432e+06,1.17051e+06,1.2223e+06,1.26933e+06,1.31133e+06,1.34814e+06,1.37968e+06,1.406e+06
8,9,Median PI,Small Island Developing States (SIDS),g,1637,Special other,1803,72076.1,75416.4,78488.2,...,88425.7,89365,90007.3,90383.8,90493.1,90351.7,89957.1,89339.6,88545.3,87598.8
9,10,Median PI,World Bank income groups,NaN,1802,Label/Separator,900,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,11,Median PI,High-income countries,h,1503,Income Group,1802,1.26309e+06,1.28277e+06,1.29877e+06,...,1.32261e+06,1.31946e+06,1.31569e+06,1.31204e+06,1.30878e+06,1.30613e+06,1.30421e+06,1.30315e+06,1.30298e+06,1.30354e+06
11,12,Median PI,Middle-income countries,h,1517,Income Group,1802,5.75305e+06,6.01603e+06,6.25258e+06,...,7.03371e+06,7.10843e+06,7.15989e+06,7.19066e+06,7.20352e+06,7.20117e+06,7.18606e+06,7.16102e+06,7.12677e+06,7.0824e+06
12,13,Median PI,Upper-middle-income countries,h,1502,Income Group,1517,2.65482e+06,2.71849e+06,2.76314e+06,...,2.77755e+06,2.74521e+06,2.70571e+06,2.66187e+06,2.61535e+06,2.5673e+06,2.51918e+06,2.47233e+06,2.42675e+06,2.38061e+06
13,14,Median PI,Lower-middle-income countries,h,1501,Income Group,1517,3.09824e+06,3.29754e+06,3.48944e+06,...,4.25616e+06,4.36323e+06,4.45418e+06,4.52879e+06,4.58818e+06,4.63387e+06,4.66687e+06,4.68869e+06,4.70001e+06,4.70179e+06
14,15,Median PI,Low-income countries,h,1500,Income Group,1802,775711,882519,993853,...,1.59782e+06,1.71951e+06,1.83814e+06,1.95228e+06,2.06064e+06,2.16218e+06,2.25591e+06,2.34118e+06,2.41753e+06,2.48483e+06
15,16,Median PI,No income group available,NaN,1518,Income Group,1802,2943.57,3115.48,3286.59,...,3966,4065.78,4160.29,4250.73,4336.33,4415.24,4485.13,4544,4590.45,4624.34
16,17,Median PI,Geographic regions,i,1840,Label/Separator,900,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,18,Median PI,Africa,j,903,Region,1840,1.3406e+06,1.50894e+06,1.68832e+06,...,2.69784e+06,2.90498e+06,3.10893e+06,3.30753e+06,3.49876e+06,3.68057e+06,3.85083e+06,4.00814e+06,4.15145e+06,4.28013e+06
18,19,Median PI,Asia,k,935,Region,1840,4.64105e+06,4.82263e+06,4.97409e+06,...,5.30166e+06,5.28922e+06,5.25644e+06,5.20654e+06,5.14276e+06,5.06851e+06,4.98691e+06,4.90115e+06,4.81231e+06,4.71991e+06
19,20,Median PI,Europe,l,908,Region,1840,747636,745791,741303,...,700121,688790,677295,666591,657283,649589,643399,638369,633921,629563
20,21,Median PI,Latin America and the Caribbean,m,904,Region,1840,653962,681896,706254,...,766792,767495,764717,758723,749876,738620,725502,711056,695753,679993
21,22,Median PI,Northern America,n,905,Region,1840,368870,379851,390599,...,432148,439379,446903,454369,461329,467639,473464,479097,484875,490889
22,23,Median PI,Oceania,o,909,Region,1840,42677.8,45334.5,47919,...,59538.4,61611.5,63592.6,65486.5,67282.1,68973.6,70563.2,72084,73545.1,74915.6
23,24,Median PI,Sustainable Development Goal (SDG) regions,p,1828,Label/Separator,900,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,25,Median PI,SUB-SAHARAN AFRICA,NaN,947,SDG region,1828,1.09437e+06,1.24117e+06,1.39989e+06,...,2.30723e+06,2.49658e+06,2.68401e+06,2.86735e+06,3.04455e+06,3.21353e+06,3.37215e+06,3.51914e+06,3.65367e+06,3.77527e+06
25,26,Median PI,Eastern Africa,NaN,910,Subregion,947,445406,505292,569705,...,923483,994888,1.06464e+06,1.1319e+06,1.19595e+06,1.25622e+06,1.31223e+06,1.36358e+06,1.41012e+06,1.45184e+06
26,27,Median PI,Burundi,NaN,108,Country/Area,910,11890.8,13763.9,15772.8,...,27995.1,30700.5,33408.1,36106.5,38790.5,41427.1,43993.3,46451.2,48760.9,50904.1
27,28,Median PI,Comoros,NaN,174,Country/Area,910,869.595,965.002,1063.11,...,1570.74,1665.91,1755.99,1840.74,1918.99,1989.64,2052.31,2106.04,2150.76,2186.51
28,29,Median PI,Djibouti,NaN,262,Country/Area,910,988.002,1056.06,1116.71,...,1324.94,1345.83,1358.41,1364.16,1365.22,1363.43,1359.26,1352.59,1343.3,1331.66
29,30,Median PI,Eritrea,NaN,232,Country/Area,910,3546.43,3865.96,4240.22,...,6426.91,6836.13,7231.48,7605.16,7945.71,8247.77,8509.62,8731.46,8915.29,9061.78

In [10]:
df_working.columns

Index([                               'Index',
                                    'Variant',
       'Region, subregion, country or area *',
                                      'Notes',
                                 'Unnamed: 4',
                                       'Type',
                                 'Unnamed: 6',
                                         2020,
                                         2025,
                                         2030,
                                         2035,
                                         2040,
                                         2045,
                                         2050,
                                         2055,
                                         2060,
                                         2065,
                                         2070,
                                         2075,
                                         2080,
                                         2085,
                                         2090,
                                         2095,
                                         2100],
      dtype='object')

In [11]:
countries_of_interest = ['China', 'Japan', 'Germany', "Republic of Korea", "United States of America", 'United Kingdom']

In [12]:
df_total.columns

Index([                             'Index',
                                  'Variant',
       'Region, subregion, country or area',
                                    'Notes',
                               'Unnamed: 4',
                                     'Type',
                               'Unnamed: 6',
                                       2020,
                                       2025,
                                       2030,
                                       2035,
                                       2040,
                                       2045,
                                       2050,
                                       2055,
                                       2060,
                                       2065,
                                       2070,
                                       2075,
                                       2080,
                                       2085,
                                       2090,
                                       2095,
                                       2100],
      dtype='object')

In [13]:
df_total.columns.values

array(['Index', 'Variant', 'Region, subregion, country or area', 'Notes',
       'Unnamed: 4', 'Type', 'Unnamed: 6', 2020, 2025, 2030, 2035, 2040,
       2045, 2050, 2055, 2060, 2065, 2070, 2075, 2080, 2085, 2090, 2095,
       2100], dtype=object)

In [14]:
df_population = df_total[df_total['Region, subregion, country or area'].isin(countries_of_interest)]
df_working_pop = df_working[df_working['Region, subregion, country or area *'].isin(countries_of_interest)]

In [15]:
df_population

,Index,Variant,"Region, subregion, country or area",Notes,Unnamed: 4,Type,Unnamed: 6,2020,2025,2030,...,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
127,128,Median PI,China,9,156,Country/Area,906,1.43932e+06,1.45791e+06,1.46434e+06,...,1.36959e+06,1.33303e+06,1.29528e+06,1.25805e+06,1.22158e+06,1.18589e+06,1.1518e+06,1.12047e+06,1.09212e+06,1.06499e+06
132,133,Median PI,Japan,NaN,392,Country/Area,906,126476,123976,120758,...,102135,98325.8,94366.3,90472.4,86926.9,83924.6,81338.4,79047.1,76939.1,74959.4
134,135,Median PI,Republic of Korea,NaN,410,Country/Area,906,51269.2,51339.4,51152.1,...,44856.8,42701.6,40565.2,38545.6,36663.3,34934.4,33354.5,31918.1,30624.3,29542
255,256,Median PI,United Kingdom,29,826,Country/Area,924,67886,69273.6,70485.5,...,74641.5,75060.5,75428.3,75815.1,76194.7,76534.8,76858.6,77220.1,77629.9,78053.3
277,278,Median PI,Germany,NaN,276,Country/Area,926,83783.9,83515,83135.6,...,78999.4,77961.7,77115.6,76466.6,75914.1,75401.7,75000.6,74769.7,74702.8,74740.6
288,289,Median PI,United States of America,35,840,Country/Area,918,331003,340400,349642,...,385335,391495,397876,404174,409993,415197,419937,424470,429082,433854

In [16]:
df_population.rename(columns={'Region, subregion, country or area':'country'}, inplace=True) 
df_working_pop.rename(columns={'Region, subregion, country or area *':'country'}, inplace=True)

/Users/brianmckean/opt/anaconda3/envs/econ/lib/python3.7/site-packages/pandas/core/frame.py:4238: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)

In [17]:
df_population

,Index,Variant,country,Notes,Unnamed: 4,Type,Unnamed: 6,2020,2025,2030,...,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
127,128,Median PI,China,9,156,Country/Area,906,1.43932e+06,1.45791e+06,1.46434e+06,...,1.36959e+06,1.33303e+06,1.29528e+06,1.25805e+06,1.22158e+06,1.18589e+06,1.1518e+06,1.12047e+06,1.09212e+06,1.06499e+06
132,133,Median PI,Japan,NaN,392,Country/Area,906,126476,123976,120758,...,102135,98325.8,94366.3,90472.4,86926.9,83924.6,81338.4,79047.1,76939.1,74959.4
134,135,Median PI,Republic of Korea,NaN,410,Country/Area,906,51269.2,51339.4,51152.1,...,44856.8,42701.6,40565.2,38545.6,36663.3,34934.4,33354.5,31918.1,30624.3,29542
255,256,Median PI,United Kingdom,29,826,Country/Area,924,67886,69273.6,70485.5,...,74641.5,75060.5,75428.3,75815.1,76194.7,76534.8,76858.6,77220.1,77629.9,78053.3
277,278,Median PI,Germany,NaN,276,Country/Area,926,83783.9,83515,83135.6,...,78999.4,77961.7,77115.6,76466.6,75914.1,75401.7,75000.6,74769.7,74702.8,74740.6
288,289,Median PI,United States of America,35,840,Country/Area,918,331003,340400,349642,...,385335,391495,397876,404174,409993,415197,419937,424470,429082,433854

In [18]:
year_columns = [x for x in df_population.columns if isinstance(x, int) and str(x).startswith('2')]

In [19]:
year_columns

[2020,
 2025,
 2030,
 2035,
 2040,
 2045,
 2050,
 2055,
 2060,
 2065,
 2070,
 2075,
 2080,
 2085,
 2090,
 2095,
 2100]

In [20]:
keep_columns = ['country']

In [21]:
keep_columns.extend(year_columns)

In [22]:
keep_columns

['country',
 2020,
 2025,
 2030,
 2035,
 2040,
 2045,
 2050,
 2055,
 2060,
 2065,
 2070,
 2075,
 2080,
 2085,
 2090,
 2095,
 2100]

In [23]:
future_population = df_population[keep_columns]

In [24]:
future_working = df_working_pop[keep_columns]

In [25]:
future_working

,country,2020,2025,2030,2035,2040,2045,2050,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
126,China,1.01213e+06,1.00665e+06,986500,943330,898371,871033,838379,779252,748756,726990,707767,684607,657269,631307,611210,594785,579012
131,Japan,74816.1,72644.2,70043.6,66217.9,60849.8,56868.5,53658.7,51224.9,49358.6,47495.8,45667.9,43744.5,41887.9,40594.8,39640.4,38782.8,37861.2
133,Republic of Korea,36742.7,35065.9,33142.8,30794.6,28368.6,26296,24371.9,22821.6,20992.7,19395.3,18398,17501.5,16608.5,16059,15630.9,15196.8,14727.2
230,United Kingdom,43222.6,43574.6,43642.4,43561.9,43809.8,43954.1,43743.1,43404.9,43266.2,43401.8,43720.2,43647.3,43366.8,43255.9,43195,43238.9,43340.6
248,Germany,53920.8,52032.9,49484.5,47526.6,46918.1,46307.7,45203,43939.5,43122.9,42480.9,42206.2,42156.4,42012.1,41541.5,41146.5,40860.6,40714.7
254,United States of America,215143,216670,217674,220266,224297,228634,231759,233283,233552,234517,235755,236905,239027,241391,243088,244389,245767

In [26]:
future_population

,country,2020,2025,2030,2035,2040,2045,2050,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
127,China,1.43932e+06,1.45791e+06,1.46434e+06,1.46108e+06,1.44903e+06,1.42931e+06,1.40241e+06,1.36959e+06,1.33303e+06,1.29528e+06,1.25805e+06,1.22158e+06,1.18589e+06,1.1518e+06,1.12047e+06,1.09212e+06,1.06499e+06
132,Japan,126476,123976,120758,117166,113356,109529,105804,102135,98325.8,94366.3,90472.4,86926.9,83924.6,81338.4,79047.1,76939.1,74959.4
134,Republic of Korea,51269.2,51339.4,51152.1,50685,49783.7,48479.7,46829.9,44856.8,42701.6,40565.2,38545.6,36663.3,34934.4,33354.5,31918.1,30624.3,29542
255,United Kingdom,67886,69273.6,70485.5,71548.8,72486.9,73346.4,74082,74641.5,75060.5,75428.3,75815.1,76194.7,76534.8,76858.6,77220.1,77629.9,78053.3
277,Germany,83783.9,83515,83135.6,82650.1,82003.6,81148.1,80104,78999.4,77961.7,77115.6,76466.6,75914.1,75401.7,75000.6,74769.7,74702.8,74740.6
288,United States of America,331003,340400,349642,358691,366572,373343,379419,385335,391495,397876,404174,409993,415197,419937,424470,429082,433854

In [27]:
pwd

'/Users/brianmckean/Dropbox/projects/econ/population'

In [28]:
data_dir = '../data/'

In [29]:
future_pop_file = 'future_population_total.csv'
future_work_file = 'future_working_total.csv'

In [30]:
future_pop_path = os.path.join(data_dir, future_pop_file)
future_work_path = os.path.join(data_dir, future_work_file)

In [31]:
future_population['country'] = future_population['country'].map(lambda x: 'South Korea' if 'korea' in x.lower() else x)
future_population['country'] = future_population['country'].map(lambda x: 'United States' if 'united states' in x.lower() else x)
future_working['country'] = future_working['country'].map(lambda x: 'South Korea' if 'korea' in x.lower() else x)
future_working['country'] = future_working['country'].map(lambda x: 'United States' if 'united states' in x.lower() else x)

/Users/brianmckean/opt/anaconda3/envs/econ/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/brianmckean/opt/anaconda3/envs/econ/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/brianmckean/opt/anaconda3/envs/econ/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/brianmckean/opt/anaconda3/envs/econ/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [32]:
future_population

,country,2020,2025,2030,2035,2040,2045,2050,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
127,China,1.43932e+06,1.45791e+06,1.46434e+06,1.46108e+06,1.44903e+06,1.42931e+06,1.40241e+06,1.36959e+06,1.33303e+06,1.29528e+06,1.25805e+06,1.22158e+06,1.18589e+06,1.1518e+06,1.12047e+06,1.09212e+06,1.06499e+06
132,Japan,126476,123976,120758,117166,113356,109529,105804,102135,98325.8,94366.3,90472.4,86926.9,83924.6,81338.4,79047.1,76939.1,74959.4
134,South Korea,51269.2,51339.4,51152.1,50685,49783.7,48479.7,46829.9,44856.8,42701.6,40565.2,38545.6,36663.3,34934.4,33354.5,31918.1,30624.3,29542
255,United Kingdom,67886,69273.6,70485.5,71548.8,72486.9,73346.4,74082,74641.5,75060.5,75428.3,75815.1,76194.7,76534.8,76858.6,77220.1,77629.9,78053.3
277,Germany,83783.9,83515,83135.6,82650.1,82003.6,81148.1,80104,78999.4,77961.7,77115.6,76466.6,75914.1,75401.7,75000.6,74769.7,74702.8,74740.6
288,United States,331003,340400,349642,358691,366572,373343,379419,385335,391495,397876,404174,409993,415197,419937,424470,429082,433854

In [33]:
temp = future_population.set_index('country')
del temp.index.name
temp = temp/1000

future_population = temp.transpose()
temp = future_working.set_index('country')
del temp.index.name
temp = temp/1000

future_working = temp.transpose()

In [34]:
future_population

        China    Japan South Korea United Kingdom  Germany United States
2020  1439.32  126.476     51.2692         67.886  83.7839       331.003
2025  1457.91  123.976     51.3394        69.2736   83.515         340.4
2030  1464.34  120.758     51.1521        70.4855  83.1356       349.642
2035  1461.08  117.166      50.685        71.5488  82.6501       358.691
2040  1449.03  113.356     49.7837        72.4869  82.0036       366.572
2045  1429.31  109.529     48.4797        73.3464  81.1481       373.343
2050  1402.41  105.804     46.8299         74.082   80.104       379.419
2055  1369.59  102.135     44.8568        74.6415  78.9994       385.335
2060  1333.03  98.3258     42.7016        75.0605  77.9617       391.495
2065  1295.28  94.3663     40.5652        75.4283  77.1156       397.876
2070  1258.05  90.4724     38.5456        75.8151  76.4666       404.174
2075  1221.58  86.9269     36.6633        76.1947  75.9141       409.993
2080  1185.89  83.9246     34.9344        76.5348  75.4017       415.197
2085   1151.8  81.3384     33.3545        76.8586  75.0006       419.937
2090  1120.47  79.0471     31.9181        77.2201  74.7697        424.47
2095  1092.12  76.9391     30.6243        77.6299  74.7028       429.082
2100  1064.99  74.9594      29.542        78.0533  74.7406       433.854

In [35]:
future_working

        China    Japan South Korea United Kingdom  Germany United States
2020  1012.13  74.8161     36.7427        43.2226  53.9208       215.143
2025  1006.65  72.6442     35.0659        43.5746  52.0329        216.67
2030    986.5  70.0436     33.1428        43.6424  49.4845       217.674
2035   943.33  66.2179     30.7946        43.5619  47.5266       220.266
2040  898.371  60.8498     28.3686        43.8098  46.9181       224.297
2045  871.033  56.8685      26.296        43.9541  46.3077       228.634
2050  838.379  53.6587     24.3719        43.7431   45.203       231.759
2055  779.252  51.2249     22.8216        43.4049  43.9395       233.283
2060  748.756  49.3586     20.9927        43.2662  43.1229       233.552
2065   726.99  47.4958     19.3953        43.4018  42.4809       234.517
2070  707.767  45.6679      18.398        43.7202  42.2062       235.755
2075  684.607  43.7445     17.5015        43.6473  42.1564       236.905
2080  657.269  41.8879     16.6085        43.3668  42.0121       239.027
2085  631.307  40.5948      16.059        43.2559  41.5415       241.391
2090   611.21  39.6404     15.6309         43.195  41.1465       243.088
2095  594.785  38.7828     15.1968        43.2389  40.8606       244.389
2100  579.012  37.8612     14.7272        43.3406  40.7147       245.767

In [36]:
future_population.reset_index(inplace=True)
future_population = future_population.rename(columns={'index': 'Year'})
future_working.reset_index(inplace=True)
future_working = future_working.rename(columns={'index': 'Year'})

In [37]:
future_population

    Year    China    Japan South Korea United Kingdom  Germany United States
0   2020  1439.32  126.476     51.2692         67.886  83.7839       331.003
1   2025  1457.91  123.976     51.3394        69.2736   83.515         340.4
2   2030  1464.34  120.758     51.1521        70.4855  83.1356       349.642
3   2035  1461.08  117.166      50.685        71.5488  82.6501       358.691
4   2040  1449.03  113.356     49.7837        72.4869  82.0036       366.572
5   2045  1429.31  109.529     48.4797        73.3464  81.1481       373.343
6   2050  1402.41  105.804     46.8299         74.082   80.104       379.419
7   2055  1369.59  102.135     44.8568        74.6415  78.9994       385.335
8   2060  1333.03  98.3258     42.7016        75.0605  77.9617       391.495
9   2065  1295.28  94.3663     40.5652        75.4283  77.1156       397.876
10  2070  1258.05  90.4724     38.5456        75.8151  76.4666       404.174
11  2075  1221.58  86.9269     36.6633        76.1947  75.9141       409.993
12  2080  1185.89  83.9246     34.9344        76.5348  75.4017       415.197
13  2085   1151.8  81.3384     33.3545        76.8586  75.0006       419.937
14  2090  1120.47  79.0471     31.9181        77.2201  74.7697        424.47
15  2095  1092.12  76.9391     30.6243        77.6299  74.7028       429.082
16  2100  1064.99  74.9594      29.542        78.0533  74.7406       433.854

In [38]:
future_working

    Year    China    Japan South Korea United Kingdom  Germany United States
0   2020  1012.13  74.8161     36.7427        43.2226  53.9208       215.143
1   2025  1006.65  72.6442     35.0659        43.5746  52.0329        216.67
2   2030    986.5  70.0436     33.1428        43.6424  49.4845       217.674
3   2035   943.33  66.2179     30.7946        43.5619  47.5266       220.266
4   2040  898.371  60.8498     28.3686        43.8098  46.9181       224.297
5   2045  871.033  56.8685      26.296        43.9541  46.3077       228.634
6   2050  838.379  53.6587     24.3719        43.7431   45.203       231.759
7   2055  779.252  51.2249     22.8216        43.4049  43.9395       233.283
8   2060  748.756  49.3586     20.9927        43.2662  43.1229       233.552
9   2065   726.99  47.4958     19.3953        43.4018  42.4809       234.517
10  2070  707.767  45.6679      18.398        43.7202  42.2062       235.755
11  2075  684.607  43.7445     17.5015        43.6473  42.1564       236.905
12  2080  657.269  41.8879     16.6085        43.3668  42.0121       239.027
13  2085  631.307  40.5948      16.059        43.2559  41.5415       241.391
14  2090   611.21  39.6404     15.6309         43.195  41.1465       243.088
15  2095  594.785  38.7828     15.1968        43.2389  40.8606       244.389
16  2100  579.012  37.8612     14.7272        43.3406  40.7147       245.767

In [39]:
future_population.to_csv(future_pop_path, index=False)

In [40]:
future_working.to_csv(future_work_path, index=False)